spring:
  application:
    name: wallet
  data.mongodb:
    host: mongo1
    port: 27017
    database: wallet

server.port: 8888

kafka:
  bootstrapAddress: broker:29092
  topic: wallet.transactions
  group: transactions-1


